"""Implement Chama and Membership models

Revision ID: 3d353c840601
Revises: 4d708d488560
Create Date: 2025-11-06 21:07:35.782916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d353c840601'
down_revision: Union[str, Sequence[str], None] = '4d708d488560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamas_id'), 'chamas', ['id'], unique=False)
    op.create_index(op.f('ix_chamas_name'), 'chamas', ['name'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chama_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    op.add_column('contributions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('contributions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('contributions', sa.Column('chama_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('contributions_member_id_fkey'), 'contributions', type_='foreignkey')
    op.create_foreign_key(None, 'contributions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'contributions', 'chamas', ['chama_id'], ['id'])
    op.drop_column('contributions', 'member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.create_foreign_key(op.f('contributions_member_id_fkey'), 'contributions', 'members', ['member_id'], ['id'])
    op.drop_column('contributions', 'chama_id')
    op.drop_column('contributions', 'user_id')
    op.drop_column('contributions', 'created_at')
    op.drop_index(op.f('ix_memberships_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_chamas_name'), table_name='chamas')
    op.drop_index(op.f('ix_chamas_id'), table_name='chamas')
    op.drop_table('chamas')
    # ### end Alembic commands ###
