"""Add role to memberships

Revision ID: a92d56187d64
Revises: 3d353c840601
Create Date: 2025-11-15 18:57:17.061814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92d56187d64'
down_revision: Union[str, Sequence[str], None] = '3d353c840601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_chamas_name'), table_name='chamas')
    op.create_unique_constraint(None, 'chamas', ['name'])
    op.add_column('contributions', sa.Column('member_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('contributions_user_id_fkey'), 'contributions', type_='foreignkey')
    op.create_foreign_key(None, 'contributions', 'memberships', ['member_id'], ['id'])
    op.drop_column('contributions', 'user_id')
    op.alter_column('memberships', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('memberships', 'chama_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('memberships', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('owner', 'treasurer', 'member', name='membershiprole'),
               nullable=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('role', sa.Enum('owner', 'treasurer', 'member', name='userrole'), server_default='member', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'is_active')
    op.alter_column('memberships', 'role',
               existing_type=sa.Enum('owner', 'treasurer', 'member', name='membershiprole'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('memberships', 'chama_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('memberships', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('contributions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.create_foreign_key(op.f('contributions_user_id_fkey'), 'contributions', 'users', ['user_id'], ['id'])
    op.drop_column('contributions', 'member_id')
    op.drop_constraint(None, 'chamas', type_='unique')
    op.create_index(op.f('ix_chamas_name'), 'chamas', ['name'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('members_pkey'))
    )
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=False)
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    # ### end Alembic commands ###
